# Generated by Django 5.0.2 on 2024-04-22 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_member_joined_date_member_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ejer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ejer_navn', models.CharField(max_length=255)),
                ('Ejer_efternavn', models.CharField(max_length=255)),
                ('Ejer_email', models.CharField(max_length=255)),
                ('Ejer_Telefon', models.IntegerField(null=True)),
            ],
        ),
    ]
