# Generated by Django 5.0.2 on 2024-05-01 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_ejer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sommerhus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Sommerhus_ID', models.CharField(max_length=2)),
                ('Adresse', models.CharField(max_length=255)),
                ('Plads_til', models.CharField(max_length=1)),
            ],
        ),
    ]
