# Generated by Django 5.0.2 on 2024-05-01 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_sommerhus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sommerhus',
            name='Sommerhus_ID',
        ),
        migrations.AddField(
            model_name='sommerhus',
            name='Ejer_id',
            field=models.IntegerField(null=True),
        ),
    ]
